# 时区，如：Asia/Shanghai（上海时区）
time-zone: Asia/Shanghai

# 监听端口
port: 8080

# 应用的上下文路径，也可以称为项目路径，是构成url地址的一部分
context-path: /

# 数据库配置
db:
  # driver name
  driver: sqlite3
  # data source name
  dns: C:\Users\xiangqian\Desktop\tmp\note\data\database.db
  max-open-conns: 2
  conn-max-lifetime: 0
  max-idle-conns: 1
  conn-max-idle-time: 1

# 物理文件数据目录
data-dir: ./data

# 是否开放注册功能
open-signup: true
