server:
  port: 1520
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB

  # 数据源配置
  datasource:
    # SQLite驱动
    # SQLite支持并发读取，但是不支持并发写入操作
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${NOTE_DATASOURCE:./data/database.db}
    # 指定使用的数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中最大连接数（包括空闲和正在使用的连接）
      maximum-pool-size: 1
      # 池中最小空闲连接数量
      minimum-idle: 1

  # 模板配置
  thymeleaf:
    # 是否使用页面缓存
    cache: false
