// DB
// https://pkg.go.dev/github.com/mattn/go-sqlite3
// @author xiangqian
// @date 20:10 2022/12/21
package db

import "database/sql"

type Db interface {
	// Begin 开启事务
	// Begin starts a transaction. The default isolation level is dependent on the driver.
	Begin() error

	// Add 新增
	// returns the integer generated by the database in response to a command.
	// Typically this will be from an "auto increment" column when inserting a new row.
	// Not all databases support this feature, and the syntax of such statements varies.
	// return insertId
	Add(sql string, args ...any) (int64, error)

	// Del 删除
	// returns the number of rows affected by an update, insert, or delete. Not every database or database driver may support this.
	// return affect
	Del(sql string, args ...any) (int64, error)

	// Upd 更新
	// returns the number of rows affected by an update, insert, or delete. Not every database or database driver may support this.
	Upd(sql string, args ...any) (int64, error)

	// Qry 查询
	Qry(sql string, args ...any) (*sql.Rows, error)

	// Commit 提交事务
	Commit() error

	// Rollback 回滚事务
	Rollback() error

	// Close 关闭资源
	Close() error
}
